name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions: write-all    

jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:dev
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Allure Report steps
      - name: Setup Allure History
        uses: actions/checkout@v4.2.2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.11
        if: always()
        with:
          allure_results: ./out/allure-results
          allure_history: ./gh-pages/allure-history
      - name: Push to GitHub Pages branch
        if: always()
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: ./gh-pages/allure-history
          github_token: ${{ secrets.GITHUB_TOKEN }}
